# Importing the Libraries

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Data importing

In [2]:
data=pd.read_csv('/kaggle/input/supermarket/GroceryStoreDataSet.csv')
data

                MILK,BREAD,BISCUIT
0    BREAD,MILK,BISCUIT,CORNFLAKES
1              BREAD,TEA,BOURNVITA
2             JAM,MAGGI,BREAD,MILK
3                MAGGI,TEA,BISCUIT
4              BREAD,TEA,BOURNVITA
5             MAGGI,TEA,CORNFLAKES
6          MAGGI,BREAD,TEA,BISCUIT
7              JAM,MAGGI,BREAD,TEA
8                       BREAD,MILK
9   COFFEE,COCK,BISCUIT,CORNFLAKES
10  COFFEE,COCK,BISCUIT,CORNFLAKES
11          COFFEE,SUGER,BOURNVITA
12               BREAD,COFFEE,COCK
13             BREAD,SUGER,BISCUIT
14         COFFEE,SUGER,CORNFLAKES
15           BREAD,SUGER,BOURNVITA
16              BREAD,COFFEE,SUGER
17              BREAD,COFFEE,SUGER
18      TEA,MILK,COFFEE,CORNFLAKES

# Data Describe

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 1 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   MILK,BREAD,BISCUIT  19 non-null     object
dtypes: object(1)
memory usage: 280.0+ bytes

In [4]:
df=data.copy()
df

                MILK,BREAD,BISCUIT
0    BREAD,MILK,BISCUIT,CORNFLAKES
1              BREAD,TEA,BOURNVITA
2             JAM,MAGGI,BREAD,MILK
3                MAGGI,TEA,BISCUIT
4              BREAD,TEA,BOURNVITA
5             MAGGI,TEA,CORNFLAKES
6          MAGGI,BREAD,TEA,BISCUIT
7              JAM,MAGGI,BREAD,TEA
8                       BREAD,MILK
9   COFFEE,COCK,BISCUIT,CORNFLAKES
10  COFFEE,COCK,BISCUIT,CORNFLAKES
11          COFFEE,SUGER,BOURNVITA
12               BREAD,COFFEE,COCK
13             BREAD,SUGER,BISCUIT
14         COFFEE,SUGER,CORNFLAKES
15           BREAD,SUGER,BOURNVITA
16              BREAD,COFFEE,SUGER
17              BREAD,COFFEE,SUGER
18      TEA,MILK,COFFEE,CORNFLAKES

In [5]:
data.columns=['items']

In [6]:
data

                             items
0    BREAD,MILK,BISCUIT,CORNFLAKES
1              BREAD,TEA,BOURNVITA
2             JAM,MAGGI,BREAD,MILK
3                MAGGI,TEA,BISCUIT
4              BREAD,TEA,BOURNVITA
5             MAGGI,TEA,CORNFLAKES
6          MAGGI,BREAD,TEA,BISCUIT
7              JAM,MAGGI,BREAD,TEA
8                       BREAD,MILK
9   COFFEE,COCK,BISCUIT,CORNFLAKES
10  COFFEE,COCK,BISCUIT,CORNFLAKES
11          COFFEE,SUGER,BOURNVITA
12               BREAD,COFFEE,COCK
13             BREAD,SUGER,BISCUIT
14         COFFEE,SUGER,CORNFLAKES
15           BREAD,SUGER,BOURNVITA
16              BREAD,COFFEE,SUGER
17              BREAD,COFFEE,SUGER
18      TEA,MILK,COFFEE,CORNFLAKES

# Transaction Encoder

In [7]:
from mlxtend.preprocessing import TransactionEncoder

# Applying Algorithms

# Apriori

In [8]:
from mlxtend .frequent_patterns import apriori,association_rules

In [9]:
transactions=[]
items=data['items'].values
print(items)
for i in range (0,len(items)):
    transactions.append(items[i].split(","))
    
print(transactions)
TE=TransactionEncoder()
trans=TE.fit(transactions).transform(transactions)
print(trans)

['BREAD,MILK,BISCUIT,CORNFLAKES' 'BREAD,TEA,BOURNVITA'
 'JAM,MAGGI,BREAD,MILK' 'MAGGI,TEA,BISCUIT' 'BREAD,TEA,BOURNVITA'
 'MAGGI,TEA,CORNFLAKES' 'MAGGI,BREAD,TEA,BISCUIT' 'JAM,MAGGI,BREAD,TEA'
 'BREAD,MILK' 'COFFEE,COCK,BISCUIT,CORNFLAKES'
 'COFFEE,COCK,BISCUIT,CORNFLAKES' 'COFFEE,SUGER,BOURNVITA'
 'BREAD,COFFEE,COCK' 'BREAD,SUGER,BISCUIT' 'COFFEE,SUGER,CORNFLAKES'
 'BREAD,SUGER,BOURNVITA' 'BREAD,COFFEE,SUGER' 'BREAD,COFFEE,SUGER'
 'TEA,MILK,COFFEE,CORNFLAKES']
[['BREAD', 'MILK', 'BISCUIT', 'CORNFLAKES'], ['BREAD', 'TEA', 'BOURNVITA'], ['JAM', 'MAGGI', 'BREAD', 'MILK'], ['MAGGI', 'TEA', 'BISCUIT'], ['BREAD', 'TEA', 'BOURNVITA'], ['MAGGI', 'TEA', 'CORNFLAKES'], ['MAGGI', 'BREAD', 'TEA', 'BISCUIT'], ['JAM', 'MAGGI', 'BREAD', 'TEA'], ['BREAD', 'MILK'], ['COFFEE', 'COCK', 'BISCUIT', 'CORNFLAKES'], ['COFFEE', 'COCK', 'BISCUIT', 'CORNFLAKES'], ['COFFEE', 'SUGER', 'BOURNVITA'], ['BREAD', 'COFFEE', 'COCK'], ['BREAD', 'SUGER', 'BISCUIT'], ['COFFEE', 'SUGER', 'CORNFLAKES'], ['BREAD', 'SUGER', 'BOURNVITA'], ['BREAD', 'COFFEE', 'SUGER'], ['BREAD', 'COFFEE', 'SUGER'], ['TEA', 'MILK', 'COFFEE', 'CORNFLAKES']]
[[ True False  True False False  True False False  True False False]
 [False  True  True False False False False False False False  True]
 [False False  True False False False  True  True  True False False]
 [ True False False False False False False  True False False  True]
 [False  True  True False False False False False False False  True]
 [False False False False False  True False  True False False  True]
 [ True False  True False False False False  True False False  True]
 [False False  True False False False  True  True False False  True]
 [False False  True False False False False False  True False False]
 [ True False False  True  True  True False False False False False]
 [ True False False  True  True  True False False False False False]
 [False  True False False  True False False False False  True False]
 [False False  True  True  True False False False False False False]
 [ True False  True False False False False False False  True False]
 [False False False False  True  True False False False  True False]
 [False  True  True False False False False False False  True False]
 [False False  True False  True False False False False  True False]
 [False False  True False  True False False False False  True False]
 [False False False False  True  True False False  True False  True]]

In [10]:
dataTE=pd.DataFrame(data = trans, columns = TE.columns_, dtype = int)
print(dataTE)

    BISCUIT  BOURNVITA  BREAD  COCK  COFFEE  CORNFLAKES  JAM  MAGGI  MILK  \
0         1          0      1     0       0           1    0      0     1
1         0          1      1     0       0           0    0      0     0
2         0          0      1     0       0           0    1      1     1
3         1          0      0     0       0           0    0      1     0
4         0          1      1     0       0           0    0      0     0
5         0          0      0     0       0           1    0      1     0
6         1          0      1     0       0           0    0      1     0
7         0          0      1     0       0           0    1      1     0
8         0          0      1     0       0           0    0      0     1
9         1          0      0     1       1           1    0      0     0
10        1          0      0     1       1           1    0      0     0
11        0          1      0     0       1           0    0      0     0
12        0          0      1     1       1           0    0      0     0
13        1          0      1     0       0           0    0      0     0
14        0          0      0     0       1           1    0      0     0
15        0          1      1     0       0           0    0      0     0
16        0          0      1     0       1           0    0      0     0
17        0          0      1     0       1           0    0      0     0
18        0          0      0     0       1           1    0      0     1

    SUGER  TEA
0       0    0
1       0    1
2       0    0
3       0    1
4       0    1
5       0    1
6       0    1
7       0    1
8       0    0
9       0    0
10      0    0
11      1    0
12      0    0
13      1    0
14      1    0
15      1    0
16      1    0
17      1    0
18      0    1

In [11]:
dataTE.head(5)

,BISCUIT,BOURNVITA,BREAD,COCK,COFFEE,CORNFLAKES,JAM,MAGGI,MILK,SUGER,TEA
0,1,0,1,0,0,1,0,0,1,0,0
1,0,1,1,0,0,0,0,0,0,0,1
2,0,0,1,0,0,0,1,1,1,0,0
3,1,0,0,0,0,0,0,1,0,0,1
4,0,1,1,0,0,0,0,0,0,0,1

# support

In [12]:
support=apriori(dataTE,min_support=0.2,use_colnames=True)
support.sort_values(by = 'support', ascending = True)

/opt/conda/lib/python3.10/site-packages/mlxtend/frequent_patterns/fpcommon.py:110: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

     support              itemsets
1   0.210526           (BOURNVITA)
6   0.210526                (MILK)
9   0.210526        (BREAD, SUGER)
10  0.210526          (BREAD, TEA)
11  0.210526  (CORNFLAKES, COFFEE)
12  0.210526       (COFFEE, SUGER)
13  0.210526          (TEA, MAGGI)
5   0.263158               (MAGGI)
0   0.315789             (BISCUIT)
4   0.315789          (CORNFLAKES)
7   0.315789               (SUGER)
8   0.368421                 (TEA)
3   0.421053              (COFFEE)
2   0.631579               (BREAD)

# confidence

In [13]:
confidence = association_rules(support, metric = 'confidence', min_threshold = 0.2)
confidence.sort_values(by = 'confidence', ascending = True)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(BREAD),(SUGER),0.631579,0.315789,0.210526,0.333333,1.055556,0.011080,1.026316,0.142857
2,(BREAD),(TEA),0.631579,0.368421,0.210526,0.333333,0.904762,-0.022161,0.947368,-0.222222
5,(COFFEE),(CORNFLAKES),0.421053,0.315789,0.210526,0.500000,1.583333,0.077562,1.368421,0.636364
6,(COFFEE),(SUGER),0.421053,0.315789,0.210526,0.500000,1.583333,0.077562,1.368421,0.636364
3,(TEA),(BREAD),0.368421,0.631579,0.210526,0.571429,0.904762,-0.022161,0.859649,-0.142857
8,(TEA),(MAGGI),0.368421,0.263158,0.210526,0.571429,2.171429,0.113573,1.719298,0.854167
1,(SUGER),(BREAD),0.315789,0.631579,0.210526,0.666667,1.055556,0.011080,1.105263,0.076923
4,(CORNFLAKES),(COFFEE),0.315789,0.421053,0.210526,0.666667,1.583333,0.077562,1.736842,0.538462
7,(SUGER),(COFFEE),0.315789,0.421053,0.210526,0.666667,1.583333,0.077562,1.736842,0.538462
9,(MAGGI),(TEA),0.263158,0.368421,0.210526,0.800000,2.171429,0.113573,3.157895,0.732143